# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voicelabels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='voicelabel',
            name='name',
            field=models.CharField(default='voicedinges', max_length=50),
            preserve_default=False,
        ),
    ]
