# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('voicelabels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoiceService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=10)),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date created')),
                ('modification_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date last modified')),
                ('active', models.BooleanField(verbose_name='Activate this voice service')),
            ],
        ),
        migrations.CreateModel(
            name='VoiceServiceElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ChoiceElement',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('options', models.CharField(max_length=10)),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.CreateModel(
            name='MessageElement',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('final_element', models.BooleanField(default=False, verbose_name='This element will terminate the call')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='voicelabels.VoiceLabel')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.CreateModel(
            name='PresentDataElement',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.AddField(
            model_name='voiceservice',
            name='start_element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_development_voiceservice_related', to='service_development.VoiceServiceElement'),
        ),
        migrations.AddField(
            model_name='messageelement',
            name='next_element',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_messageelement_related', to='service_development.VoiceServiceElement'),
        ),
    ]
