# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 20:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0002_auto_20170313_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voiceserviceelement',
            name='name1',
        ),
        migrations.AlterField(
            model_name='voiceserviceelement',
            name='description',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='voiceserviceelement',
            name='name',
            field=models.CharField(max_length=40),
        ),
    ]
