# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('voicelabels', '0002_voicelabel_name'),
        ('service_development', '0003_auto_20170313_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicelabels.VoiceLabel')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.CreateModel(
            name='ChoiceOption',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('audio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicelabels.VoiceLabel')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.CreateModel(
            name='MessagePresentation',
            fields=[
                ('voiceserviceelement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='service_development.VoiceServiceElement')),
                ('final_element', models.BooleanField(default=False, verbose_name='This element will terminate the call')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='voicelabels.VoiceLabel')),
                ('next_element', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_development_messagepresentation_related', to='service_development.VoiceServiceElement')),
            ],
            bases=('service_development.voiceserviceelement',),
        ),
        migrations.RenameModel(
            old_name='PresentDataElement',
            new_name='DataPresentation',
        ),
        migrations.RemoveField(
            model_name='choiceelement',
            name='voiceserviceelement_ptr',
        ),
        migrations.RemoveField(
            model_name='messageelement',
            name='message',
        ),
        migrations.RemoveField(
            model_name='messageelement',
            name='next_element',
        ),
        migrations.RemoveField(
            model_name='messageelement',
            name='voiceserviceelement_ptr',
        ),
        migrations.DeleteModel(
            name='ChoiceElement',
        ),
        migrations.DeleteModel(
            name='MessageElement',
        ),
        migrations.AddField(
            model_name='choiceoption',
            name='redirect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_development_choiceoption_related', to='service_development.VoiceServiceElement'),
        ),
    ]
