# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-13 21:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_development', '0004_auto_20170313_2109'),
    ]

    operations = [
        migrations.AddField(
            model_name='choiceoption',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service_development_choiceoption_parent_related', to='service_development.Choice'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='choiceoption',
            name='redirect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_development_choiceoption_redirect_related', to='service_development.VoiceServiceElement'),
        ),
    ]
